Remove source/target level 1.7 settings in desugar build
This uses the default settings (java 1.8) and hence avoids
the following compile errors:

tools/external/desugar/java/com/google/devtools/common/options/OptionsParser.java:712:
error: lambda expressions are not supported in -source 1.7
    parseWithSourceFunction(priority, o -> source, args);
                                        ^

Test: bazel build desugar
Change-Id: Ib60136076bece2e19dc5d0d56aaa52b0eeef8532